/*
 * Copyright © 2024 Anthoine Bourgeois <anthoine.bourgeois@gmail.com>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include "wrap.h"

void pvrsrv_bridge_open_dispclass_device_pre(int fd,
		PVRSRV_BRIDGE_PACKAGE *param)
{
	PVRSRV_BRIDGE_IN_OPEN_DISPCLASS_DEVICE *in = param->pvParamIn;

	printf("\t\tdevice id:\t%08x\n", in->ui32DeviceID);
	printf("\t\tdev cookie:\t%p\n", in->hDevCookie);
}

void pvrsrv_bridge_open_dispclass_device_post(int fd,
		PVRSRV_BRIDGE_PACKAGE *param)
{
	PVRSRV_BRIDGE_OUT_OPEN_DISPCLASS_DEVICE *out = param->pvParamOut;

	print_error(out->eError);
	printf("\t\tdevice km:\t%p\n", out->hDeviceKM);
}

void pvrsrv_bridge_get_dispclass_info_pre(int fd,
		PVRSRV_BRIDGE_PACKAGE *param)
{
	PVRSRV_BRIDGE_IN_GET_DISPCLASS_INFO *in = param->pvParamIn;

	printf("\t\tdevice km:\t%p\n", in->hDeviceKM);
}

static void print_displayinfo(DISPLAY_INFO *displayinfo)
{
	if (!displayinfo) {
		return;
	}

	printf("\t\tmax swap:\t%08x\n", displayinfo->ui32MaxSwapChains);
	printf("\t\tmax swapbuf:\t%08x\n", displayinfo->ui32MaxSwapChainBuffers);
	printf("\t\tmin intval:\t%08x\n", displayinfo->ui32MinSwapInterval);
	printf("\t\tmax intval:\t%08x\n", displayinfo->ui32MaxSwapInterval);
	printf("\t\tphys width:\t%08x\n", displayinfo->ui32PhysicalWidthmm);
	printf("\t\tphys height:\t%08x\n", displayinfo->ui32PhysicalHeightmm);
	printf("\t\tdisp name:\t'%s'\n", displayinfo->szDisplayName);
#if defined(SUPPORT_HW_CURSOR)
	printf("\t\tcurs wigth:\t%04x\n", displayinfo->ui32CursorWidth);
	printf("\t\tcurs height:\t%04x\n", displayinfo->ui32CursorHeight);
#endif
}

void pvrsrv_bridge_get_dispclass_info_post(int fd,
		PVRSRV_BRIDGE_PACKAGE *param)
{
	PVRSRV_BRIDGE_OUT_GET_DISPCLASS_INFO *out = param->pvParamOut;

	print_error(out->eError);
	print_displayinfo(&out->sDisplayInfo);
}

void pvrsrv_bridge_close_dispclass_device_pre(int fd,
		PVRSRV_BRIDGE_PACKAGE *param)
{
	PVRSRV_BRIDGE_IN_CLOSE_DISPCLASS_DEVICE *in = param->pvParamIn;

	printf("\t\tdevice km:\t%p\n", in->hDeviceKM);
}

void pvrsrv_bridge_close_dispclass_device_post(int fd,
		PVRSRV_BRIDGE_PACKAGE *param)
{
	PVRSRV_BRIDGE_RETURN *out = param->pvParamOut;

	print_error(out->eError);
}

void pvrsrv_bridge_enum_dispclass_formats_pre(int fd,
		PVRSRV_BRIDGE_PACKAGE *param)
{
	PVRSRV_BRIDGE_IN_ENUM_DISPCLASS_FORMATS *in = param->pvParamIn;

	printf("\t\tdevice km:\t%p\n", in->hDeviceKM);
}

static const char *formatnames[] = {
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_UNKNOWN),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_RGB565),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_RGB555),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_RGB888),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_BGR888),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_GREY_SCALE),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_PAL12),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_PAL8),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_PAL4),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_PAL2),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_PAL1),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_ARGB1555),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_ARGB4444),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_ARGB8888),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_ABGR8888),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_YV12),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_I420),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_IMC2),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_XRGB8888),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_XBGR8888),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_BGRA8888),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_XRGB4444),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_ARGB8332),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_A2RGB10),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_A2BGR10),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_P8),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_L8),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_A8L8),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_A4L4),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_L16),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_L6V5U5),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_V8U8),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_V16U16),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_QWVU8888),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_XLVU8888),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_QWVU16),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_D16),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_D24S8),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_D24X8),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_ABGR16),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_ABGR16F),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_ABGR32),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_ABGR32F),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_B10GR11),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_GR88),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_BGR32),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_GR32),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_E5BGR9),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_RESERVED1),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_RESERVED2),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_RESERVED3),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_RESERVED4),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_RESERVED5),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_R8G8_B8G8),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_G8R8_G8B8),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_NV11),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_NV12),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_YUY2),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_YUV420),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_YUV444),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_VUY444),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_YUYV),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_YVYU),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_UYVY),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_VYUY),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_FOURCC_ORG_UYVY),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_FOURCC_ORG_YUYV),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_FOURCC_ORG_YVYU),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_FOURCC_ORG_VYUY),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_FOURCC_ORG_AYUV),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_A32B32G32R32),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_A32B32G32R32F),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_A32B32G32R32_UINT),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_A32B32G32R32_SINT),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_B32G32R32),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_B32G32R32F),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_B32G32R32_UINT),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_B32G32R32_SINT),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_G32R32),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_G32R32F),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_G32R32_UINT),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_G32R32_SINT),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_D32F),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_R32),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_R32F),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_R32_UINT),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_R32_SINT),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_A16B16G16R16),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_A16B16G16R16F),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_A16B16G16R16_SINT),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_A16B16G16R16_SNORM),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_A16B16G16R16_UINT),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_A16B16G16R16_UNORM),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_G16R16),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_G16R16F),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_G16R16_UINT),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_G16R16_UNORM),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_G16R16_SINT),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_G16R16_SNORM),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_R16),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_R16F),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_R16_UINT),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_R16_UNORM),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_R16_SINT),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_R16_SNORM),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_X8R8G8B8),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_X8R8G8B8_UNORM),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_X8R8G8B8_UNORM_SRGB),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_A8R8G8B8),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_A8R8G8B8_UNORM),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_A8R8G8B8_UNORM_SRGB),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_A8B8G8R8),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_A8B8G8R8_UINT),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_A8B8G8R8_UNORM),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_A8B8G8R8_UNORM_SRGB),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_A8B8G8R8_SINT),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_A8B8G8R8_SNORM),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_G8R8),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_G8R8_UINT),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_G8R8_UNORM),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_G8R8_SINT),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_G8R8_SNORM),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_A8),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_R8),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_R8_UINT),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_R8_UNORM),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_R8_SINT),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_R8_SNORM),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_A2B10G10R10),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_A2B10G10R10_UNORM),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_A2B10G10R10_UINT),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_B10G11R11),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_B10G11R11F),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_X24G8R32),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_G8R24),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_X8R24),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_E5B9G9R9),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_R1),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_RESERVED6),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_RESERVED7),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_RESERVED8),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_RESERVED9),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_RESERVED10),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_RESERVED11),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_RESERVED12),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_RESERVED13),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_RESERVED14),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_RESERVED15),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_RESERVED16),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_RESERVED17),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_RESERVED18),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_RESERVED19),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_RESERVED20),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_UBYTE4),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_SHORT4),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_SHORT4N),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_USHORT4N),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_SHORT2N),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_SHORT2),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_USHORT2N),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_UDEC3),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_DEC3N),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_F16_2),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_F16_4),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_L_F16),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_L_F16_REP),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_L_F16_A_F16),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_A_F16),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_B16G16R16F),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_L_F32),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_A_F32),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_L_F32_A_F32),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_PVRTC2),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_PVRTC4),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_PVRTCII2),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_PVRTCII4),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_PVRTCIII),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_PVRO8),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_PVRO88),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_PT1),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_PT2),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_PT4),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_PT8),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_PTW),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_PTB),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_MONO8),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_MONO16),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_C0_YUYV),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_C0_UYVY),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_C0_YVYU),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_C0_VYUY),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_C1_YUYV),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_C1_UYVY),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_C1_YVYU),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_C1_VYUY),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_C0_YUV420_2P_UV),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_C0_YUV420_2P_VU),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_C0_YUV420_3P),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_C1_YUV420_2P_UV),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_C1_YUV420_2P_VU),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_C1_YUV420_3P),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_A2B10G10R10F),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_B8G8R8_SINT),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_PVRF32SIGNMASK),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_ABGR4444),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_ABGR1555),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_BGR565),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_C0_4KYUV420_2P_UV),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_C0_4KYUV420_2P_VU),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_C1_4KYUV420_2P_UV),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_C1_4KYUV420_2P_VU),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_P208),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_A8P8),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_A4),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_AYUV8888),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_RAW256),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_RAW512),
	ENUM_INFO(PVRSRV_PIXEL_FORMAT_RAW1024),
};
void pvrsrv_bridge_enum_dispclass_formats_post(int fd,
		PVRSRV_BRIDGE_PACKAGE *param)
{
	PVRSRV_BRIDGE_OUT_ENUM_DISPCLASS_FORMATS *out = param->pvParamOut;
	int i;
	const char *formatname;

	print_error(out->eError);
	if (out->eError == PVRSRV_OK) {
		printf("\t\tcount:\t%08x\n", out->ui32Count);
		printf("\t\tmaxcount:\t%08x\n", PVRSRV_MAX_DC_DISPLAY_FORMATS);
		for (i = 0; i < out->ui32Count; i++) {
			formatname =
				(out->asFormat[i].pixelformat < ARRAY_SIZE(formatnames)) ?
				formatnames[out->asFormat[i].pixelformat] : NULL;
			printf("\t\tformat[%d]:\t%08x (%s)\n", i, out->asFormat[i].pixelformat,
				formatname ? formatname : "unknown");
		}
	}
}

void pvrsrv_bridge_enum_dispclass_dims_pre(int fd,
		PVRSRV_BRIDGE_PACKAGE *param)
{
	PVRSRV_BRIDGE_IN_ENUM_DISPCLASS_DIMS *in = param->pvParamIn;
	const char *formatname;

	printf("\t\tdevice km:\t%p\n", in->hDeviceKM);
	formatname =
		(in->sFormat.pixelformat < ARRAY_SIZE(formatnames)) ?
		formatnames[in->sFormat.pixelformat] : NULL;
	printf("\t\tformat:\t%08x (%s)\n", in->sFormat.pixelformat,
		formatname ? formatname : "unknown");
}

void pvrsrv_bridge_enum_dispclass_dims_post(int fd,
		PVRSRV_BRIDGE_PACKAGE *param)
{
	PVRSRV_BRIDGE_OUT_ENUM_DISPCLASS_DIMS *out = param->pvParamOut;
	int i;

	print_error(out->eError);
	if (out->eError == PVRSRV_OK) {
		printf("\t\tcount:\t%08x\n", out->ui32Count);
		printf("\t\tmax cnt:\t%08x\n", PVRSRV_MAX_DC_DISPLAY_DIMENSIONS);
		for (i = 0; i < out->ui32Count; i++) {
			printf("\t\tdim stride[%d]:\t%08x\n", i, out->asDim[i].ui32ByteStride);
			printf("\t\tdim width[%d]:\t%08x\n", i, out->asDim[i].ui32Width);
			printf("\t\tdim height[%d]:\t%08x\n", i, out->asDim[i].ui32Height);
		}
	}
}

void pvrsrv_bridge_get_dispclass_sysbuffer_pre(int fd,
		PVRSRV_BRIDGE_PACKAGE *param)
{
	PVRSRV_BRIDGE_IN_GET_DISPCLASS_SYSBUFFER *in = param->pvParamIn;

	printf("\t\tdevice km:\t%p\n", in->hDeviceKM);
}

void pvrsrv_bridge_get_dispclass_sysbuffer_post(int fd,
		PVRSRV_BRIDGE_PACKAGE *param)
{
	PVRSRV_BRIDGE_OUT_GET_DISPCLASS_SYSBUFFER *out = param->pvParamOut;

	print_error(out->eError);
	printf("\t\tbuffer:\t%p\n", out->hBuffer);
}

